### ISSUE TITLE
Calibre reported an error “Vault not found”

### ISSUE THREAD

**Issue by Pitrumo** [jm289765/highlights-to-obsidian#12]
Hello!Calibre reported an error “Vault not found”, where the plugin configuration of Calibre and the library name of Obsidian are the same, both are “note”

The following is a screenshot of the error:
![error](https://github.com/user-attachments/assets/83bf611e-cf35-4150-a895-0da0916c5224)

The following is a screenshot of Calibre configuration:
![first](https://github.com/user-attachments/assets/13d56d07-6d17-40ae-81d8-75b81b06df65)

The following is a screenshot of Obsidian configuration:
![image](https://github.com/user-attachments/assets/775eae5d-477b-4b45-bc32-35a75cf051dc)

The versions of Calibre and Obsidian are both the latest versions.

Could you please give me some solutions? Thank you!

**Comment by Pitrumo** [comment]
Solved, thank you everyone

**Comment by jm289765** [comment]
Ah, ninja'd by the OP. I'll post my response anyway, in case anyone else comes across this problem.

It looks like "note" is the name of a folder inside your Obsidian vault. The vault name can be found in the bottom left corner of the screen, where you see "Vault name" in this image.

![24-08-30_Obsidian_12-04-45](https://github.com/user-attachments/assets/8c98f99d-eb86-4ba3-937c-b29cd3e177fc)

**Comment by Pitrumo** [comment]
Ah,Thank you my hero!
