### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by sarantsatsral-qy** [jm289765/highlights-to-obsidian#3]
Hi, I learned about your plugin from Obsidian Forum, but when I tried to install it on Windows 10, this happened:
![image](https://user-images.githubusercontent.com/30141705/227408688-afd8c152-f5dd-49be-bb21-1068405c9cf7.png)

Thanks!

**Comment by jm289765** [comment]
This isn't an Obsidian plugin, it's a [calibre](https://calibre-ebook.com/) plugin. To install, open calibre and go to Preferences -> Plugins -> Get new plugins and search for Highlights to Obsidian.

For reference, [Obsidian forum post](https://forum.obsidian.md/t/calibre/7981/17).
